SELECT *FROM T_PROFESSOR;

SELECT DEPTNO , POSITION, AVG(PAY) 
FROM T_PROFESSOR 
GROUP BY DEPTNO ,POSITION
ORDER BY DEPTNO ASC, POSITION ASC;

SELECT deptno 부서번호, AVG(nvl(pay,0)) 평균급여 
FROM T_professor 
GROUP BY deptno
HAVING AVG(nvl(pay,0))>450;

SELECT *FROM t_emp;
SELECT MGR 매니저,count(*) 직원수, sum(SAL) 급여총액, avg(SAL) 평균, avg(nvl(COMM,0)) 교통비
FROM T_EMP
WHERE JOB !='PRESIDENT'
GROUP BY MGR;

SELECT *FROM T_PROFESSOR; 

SELECT DEPTNO , count(nvl(DEPTNO,0)) 총인원, avg(SYSDATE-HIREDATE) 근속평균,avg(PAY) 급여평균, avg(nvl(BONUS,0)) 보너스평균
FROM T_PROFESSOR
WHERE POSITION ='정교수' OR POSITION ='조교수'
GROUP BY DEPTNO;

SELECT *FROM T_STUDENT;

SELECT DEPTNO1 학과,max(WEIGHT)-min(WEIGHT)
FROM T_STUDENT
GROUP BY DEPTNO1 ;

SELECT DEPTNO1 학과,max(WEIGHT)-min(WEIGHT)
FROM T_STUDENT
GROUP BY DEPTNO1 
HAVING max(WEIGHT)-min(WEIGHT)>=30;


