
SELECT * FROM T_STUDENT; 
SELECT * FROM T_PROFESSOR;
SELECT * FROM T_DEPARTMENT;



SELECT a.name, b.DNAME FROM T_STUDENT a,T_DEPARTMENT b WHERE a.DEPTNO1 =b.DEPTNO ;


CREATE OR REPLACE VIEW v_stud_info ( 학생이름, 학생학과명,담당교수님이름)
AS
SELECT s.name,d.DNAME, p.NAME
FROM T_STUDENT s, T_DEPARTMENT d, T_PROFESSOR p 
WHERE s.DEPTNO1 =d.DEPTNO AND s.PROFNO=p.PROFNO ;

SELECT * FROM v_stud_info;