-- INITCAP() 함수

-- #4101
SELECT INITCAP('pretty girl') 
FROM dual; --한행짜리 dummy TABLE

--#4102
SELECT id, INITCAP(ID) ID
FROM T_STUDENT 
WHERE DEPTNO1 =201

-- LOWER(), UPPER()
-- #4103
SELECT name, id,UPPER(id) 대문자,LOWER(ID) 소문자
FROM T_STUDENT 
WHERE DEPTNO1 =201

--LENGTH / LENGTHB
-- #4104 ,#4105
SELECT name,id,LENGTHB(id) 글자수 
FROM T_STUDENT 
WHERE LENGTHB(ID) >=9;

SELECT name, LENGTH(NAME) 길이,LENGTHB(NAME) 바이트  
FROM T_STUDENT 
WHERE DEPTNO1 =201;

--CONCAT()
--#4106
SELECT CONCAT(name,position) 교수님명단 
FROM T_PROFESSOR 
WHERE DEPTNO =101;

--SUBSTR()
--#4107 , #4108, #4109
SELECT name,SUBSTR(JUMIN ,'1','6') 생년월일
FROM T_STUDENT
WHERE DEPTNO1 =101;

SELECT name,SUBSTR(JUMIN ,'1','6') 생년월일
FROM T_STUDENT
WHERE SUBSTR(JUMIN ,'3','2')= '08';

--INSTR
--#4110
SELECT INSTR('A*B*C*', '*', 1, 1) FROM dual; --2
SELECT INSTR('A*B*C*', '*', 1, 2) FROM dual; --4
SELECT INSTR('A*B*C*', '*', 3, 2) FROM dual; --6
SELECT INSTR('A*B*C*', '*', -4, 1) FROM dual; --2 음수 인덱스의 경우 검색도 음의 방향응로 진행
SELECT INSTR('A*B*C*', '*', -4, 2) FROM dual; --0
SELECT NAME,TEL ,INSTR(TEL,')',1,1) 위치 FROM T_STUDENT WHERE DEPTNO1 =101;

--#4111
SELECT name,TEL ,SUBSTR(TEL ,'1',INSTR(TEL,')',1,1)-1)
FROM T_STUDENT
WHERE DEPTNO1 =101;

--#4116
 SELECT 
	LTRIM('슈퍼슈퍼슈가맨', '슈퍼') LTRIM,
	LTRIM('슈퍼슈퍼슈가맨', '슈') LTRIM,
	LTRIM('  슈퍼슈퍼슈가맨', ' ') LTRIM,
	RTRIM('우측 공백 제거      ')RTRIM,
	TRIM('      좌우 공백 제거      ') TRIM,
	LTRIM('********1000', '*')LTRIM
FROM dual;

SELECT RTRIM(dname,'부') RTRIM FROM T_DEPT2;

--#4118
--REPLACE
SELECT REPLACE('슈퍼맨 슈퍼걸', '슈퍼', '파워') REPLACE예제 FROM dual;
SELECT REPLACE('아버지가 방에 들어간다',' ','') FROM DUAL;
SELECT REPLACE(name,SUBSTR(NAME,7,1),'#') FROM T_STUDENT WHERE DEPTNO1 =102;

--#4119,4120,4121

SELECT REPLACE(name,SUBSTR(NAME,2,1),'#') REPLACE예제 FROM T_STUDENT WHERE DEPTNO1= 101;
SELECT name,REPLACE(JUMIN,SUBSTR(JUMIN,7,7),'*******') FROM T_STUDENT WHERE DEPTNO1= 101;
SELECT NAME,TEL, REPLACE(TEL,SUBSTR(TEL,INSTR(TEL,')',1,1)+1,3),'###') FROM T_STUDENT WHERE DEPTNO1= 102;

--table 시험에 vachar ,char 
