--INSERT INTO 테이블이름
--UPDATE 테이블 이름 SET
-- DELETE FROM 테이블 이름
SELECT * FROM TEST_MEMBER ;
INSERT INTO TEST_MEMBER Values(10,'남윤주',sysdate);
SELECT *FROM TEST_MEMBER;
INSERT INTO TEST_MEMBER Values(22,'잇으환','1994-02-21');
INSERT INTO TEST_MEMBER Values(17,'윤종섭','2019-08-23');
INSERT INTO TEST_MEMBER Values('','윤종섭','2019-08-23');  --비어있는 ''를 INSERT하면 null값처리
--INSERT INTO TEST_MEMBER Values(17,'','2011-01-23');
INSERT INTO TEST_MEMBER Values(NULL,'남윤듕','2017-08-23');
SELECT *FROM TEST_MEMBER;
